### ISSUE TITLE
No defined values available.

### ISSUE THREAD

**Issue by cwillia109** [rmsolgi/geneticalgorithm#13]
https://github.com/rmsolgi/geneticalgorithm/blob/3c23d48adce9f5c70ec2a50cd1bac99a454f92ba/geneticalgorithm/geneticalgorithm.py#L89-L94

I'm working on a problem that has predefined float (or int) values and not a range of values. This does not allow for such a thing.
In a grouping GA, the alleles would be the group, and you could define them with something like:

`alleles = np.array([1, 2, 3, 7, 9)`  or `np.array(["A", "B", "C"])`

**Comment by PasaOpasen** [comment]
@cwillia109 it will be faster and better if user will write his wrapper for his aliases, it's not about concrete GA realization

I'm continueing this project here https://github.com/PasaOpasen/geneticalgorithm2
