### ISSUE TITLE
How to access final generation after the simulation was finished?

### ISSUE THREAD

**Issue by ignaspakamore** [rmsolgi/geneticalgorithm#14]
Hi, 

I need to access full generation and not only the best result. How could I do that? 

Thanks!

**Comment by PasaOpasen** [comment]
@ignaspakamore Hello!

I solved this in my fork https://github.com/PasaOpasen/geneticalgorithm2

Take a look!! Thank u

**Comment by PasaOpasen** [comment]
@ignaspakamore https://github.com/PasaOpasen/geneticalgorithm2#how-to-initialize-start-population-how-to-continue-optimization-with-new-run
