### ISSUE TITLE
Replace math.pi with np.pi and get rid of "import math"

### ISSUE THREAD

**Issue by sewkokot** [rmsolgi/geneticalgorithm#16]
Just a remark to simplify examples, since in principle anything in the math module is also in the numpy module we can import only numpy. In particular we can replace "math.pi" with "np.pi".

**Comment by PasaOpasen** [comment]
@sewkokot It doesn't matter when u write just a little example of using)

Take a look at [big update of this package](https://github.com/PasaOpasen/geneticalgorithm2)

**Comment by sewkokot** [comment]
@PasaOpasen thank you for your fork. I cloned from your repository seeing that you develop it further.

I know that it does not matter, however it will make the examples even simpler/cleaner by one line ;)
