### ISSUE TITLE
Using Genetic algorithm with random forest

### ISSUE THREAD

**Issue by pgaiwak** [rmsolgi/geneticalgorithm#2]
Hi,

Thanks a lot for writing a package for Genetic algorithms. I am using random forest regression for a prediction problem, and am using this package for optimization. I encounter a value error while implementing the code. A part of the code is given below, and the error is given after that. 

Clf is the pretrained random forest regressor, predictors_test is the set of independent variables of the test set; there are a total of 12 dependent variables

Code Snippet
------------------------------------------------------------------------------------------------
from geneticalgorithm import geneticalgorithm as ga

def f(x):
    p = clf.predict(predictors_test)
    return p
varbound=np.array([(0,100)]*12)

model=ga(function=f,dimension=12,variable_type='real',variable_boundaries=varbound)
model.run()
-------------------------------------------------------------------------------------------------

Error
--------------------------------------------------------------------------------------------------
Traceback (most recent call last):

  File "<ipython-input-50-640ff0f5af65>", line 1, in <module>
    model.run()

  File "C:\Anaconda3\lib\site-packages\geneticalgorithm\geneticalgorithm.py", line 285, in run
    obj=self.sim(var)

  File "C:\Anaconda3\lib\site-packages\geneticalgorithm\geneticalgorithm.py", line 524, in sim
    assert (obj!=None), "After "+str(self.funtimeout)+" seconds delay "+\

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
-------------------------------------------------------------------------------------------------------

While the error itself is quite generic, I am not able to figure out how to rectify it in this scenario. Please let me know if you have faced this before or if you have any insights. Any suggestions will be appreciated.

Thanks in advance.

**Comment by ZackYovel** [comment]
Hi @pgaiwak

I am not related to this project but if I may suggest an explanation to your problem, Here it is:

On the home page I saw this: "The given function to be optimized must only accept one argument and return a scalar."
Notice your function returns an ndarray as you probably know and as written in the documentation for RandomForestRegressor.
So I believe this is not a problem in the geneticalgorithm library, just in the way it is being used.

**Comment by deathlyhallows010** [comment]
Hi @pgaiwak 

I didn't understand the Idea of testing variables on test data. 
For finding the hyperparameters genetic algorithm can be used. You can use

def f(x):
   clf = randomforestclassifier(x)
   output = clf.predict(test_data) 
   return accuary(x,test_data)

Where the variable bounds should be
param_random = {
    'clf__learning_rate': list(np.logspace(np.log(0.01), np.log(1), num = 500, base=3)),
    'clf__max_depth': list(range(5, 15)),
    'clf__n_estimators': list(range(5, 35)),
    'clf__num_leaves': list(range(5, 50)),
    'clf__boosting_type': ['gbdt', 'dart'],
    'clf__colsample_bytree': list(np.linspace(0.6, 1, 500)),
    'clf__reg_lambda': list(np.linspace(0, 1, 500)),
}

Feature importance is to be used to get the importance matrix of input independent variables.

(The error you are getting is due to the passing of a variable value matrix - which is not the kind of optimization we are looking forward)

**Comment by PasaOpasen** [comment]
@pgaiwak use sklearn-deap https://github.com/rsteca/sklearn-deap for this
