### ISSUE TITLE
Feature Request: Attribute to access elite population variables

### ISSUE THREAD

**Issue by koralturkk** [rmsolgi/geneticalgorithm#20]
For optimization tasks, sometimes other good performing configurations are important to ensembling reasons. It would be nice if elite variables can be accessed. If you want, I can work on it and contribute to the project. Have a good day!

**Comment by PasaOpasen** [comment]
@koralturkk Take a look at `geneticalgorithm2` package https://github.com/PasaOpasen/geneticalgorithm2

Elit variables are always available, they are several first observations in population. What do u mean exactly?

**Comment by koralturkk** [comment]
thanks, I was wondering if there is an attribute to access elite individuals' variables. I was thinking that the result object has the following attributes only. 


`       self.report=[]
        self.test_obj=obj
        self.best_variable=var.copy()
        self.best_function=obj`

**Comment by PasaOpasen** [comment]
@koralturkk In `geneticalgorithm2` there are `model.num_elit` elit objects

So, u can get them using code:
```python
last_gen = model.output_dict['last_generation']['variablers']

elit_objects_from_last_gen = last_gen[:model.num_elit, :]
```
But I don't understand the sense of getting elit objects cuz they should be changed during optimization process

**Comment by rmsolgi** [comment]
The best solution reported is the last elite. But there is no access to other ones.
