### ISSUE TITLE
Passing parameters into objective function

### ISSUE THREAD

**Issue by edrexplore** [rmsolgi/geneticalgorithm#21]
I'd like to pass parameters into objective function to generalise the optimisation problem. e.g. f(x)=c-x where x is the variable and c a parameter that could be passed. How do I do this?

**Comment by PasaOpasen** [comment]
@edrexplore take a look at [geneticalgorithm2 package](https://github.com/PasaOpasen/geneticalgorithm2)

do u mean situation like

```python

f = lambda c, x: ...

c = 10
g = lambda x: c-x

```
???

**Comment by rmsolgi** [comment]
the input to the function must be only the variables you want to optimize. If you need other parameters you can read or define them inside the function not as its inputs.
