### ISSUE TITLE
how to initialize an initial solution?

### ISSUE THREAD

**Issue by seeingwu** [rmsolgi/geneticalgorithm#22]
Hi, can this package specify the initial solution for GA and search the optimized solution from the initial solution?

**Comment by PasaOpasen** [comment]
@seeingwu take a look at `geneticalgorithm2` package with a solving a lot of problems: https://github.com/PasaOpasen/geneticalgorithm2#how-to-initialize-start-population-how-to-continue-optimization-with-new-run

**Comment by seeingwu** [comment]
Thank you so much!
That helps a lot, I just realized there is a geneticalgorithm2 package.
That's great work.

**Comment by rmsolgi** [comment]
No
