### ISSUE TITLE
Feature request: Add option to suppress automatic plotting after run finishes

### ISSUE THREAD

**Issue by dmartintucker** [rmsolgi/geneticalgorithm#4]
Thanks for making this handy library! I'd like to request an option for disabling/suppressing the automatic plot that is generated after each model run is completed. If this is already a feature and I've somehow missed it in your documentation, I apologize the oversight.

**Comment by Freakaz0id** [comment]
Have you found a solution yet? The package works great, but these plot pop-ups prevents me from using it. I would be very greatful for a hint or fix.

**Comment by PasaOpasen** [comment]
@dmartintucker @Freakaz0id I solved this problem in my supported fork https://github.com/PasaOpasen/geneticalgorithm2

**Comment by rmsolgi** [comment]
Version 1.0.2 has this capability please reinstall the package. https://pypi.org/project/geneticalgorithm/
