### ISSUE TITLE
Initial Population

### ISSUE THREAD

**Issue by Aravgit** [rmsolgi/geneticalgorithm#5]
Hi,
Thanks for the module. Is there a way to input a specific initial population?

**Comment by PasaOpasen** [comment]
@Aravgit I think I will create it in my supported fork https://github.com/PasaOpasen/geneticalgorithm2

**Comment by PasaOpasen** [comment]
@Aravgit I solved it here https://github.com/PasaOpasen/geneticalgorithm2
