### ISSUE TITLE
Constaints from array

### ISSUE THREAD

**Issue by gaproset** [rmsolgi/geneticalgorithm#6]
Hello, is it somehow possible to create the constrains from an array, something like this:
X = [0 , 1]

arr = [ 'X[0] + X[1] < 2 ']

def f(X):
    pen=0
    for i in range( len(arr)):
        if arr[i]:
            pen=500+1000
    return np.sum(X)+pen

varbound=np.array([[0,10]]*3)
Thank you!

**Comment by rmsolgi** [comment]
If I got it correctly, yes you can. You can define a loop inside your function or do what ever else you want as long as the input of the function be variables you want to optimize and the output is the fitness value.
