### ISSUE TITLE
Feature suggestion: multiple populations

### ISSUE THREAD

**Issue by ZackYovel** [rmsolgi/geneticalgorithm#7]
Hi, If I understood the documentation correctly there is currently no way to implement multiple populations in this library, so I'd like to suggest that. If I misunderstood and there is a way, I'd be very thankful if you can point me at the place in the docs I should read in order to learn how to implement it.

**Comment by rmsolgi** [comment]
Hi, I will add a version for the multithread capability soon. This version does not do that. But thanks for your suggestion.

**Comment by PasaOpasen** [comment]
@ZackYovel I will do it in my supported fork https://github.com/PasaOpasen/geneticalgorithm2
