### ISSUE TITLE
Index out of bound error

### ISSUE THREAD

**Issue by elizabethwoodruff** [rmsolgi/geneticalgorithm#9]
Hi,
I've never really used a genetic algorithm before, so I decided to use the geneticalgorithm model since it seems rather easy to use and understand. However, it doesn't seem to work for me unless I decrease the population size by a lot. When I increase it, or even use the default 100 value, I get the following error:
|||||||||||||||||||||||||||||||||||||||||||||||||| 100.0% GA is running.../home/ewoodruff/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py:87: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
Traceback (most recent call last):
  File "ApplicationHandler.py", line 387, in <module>
    main()
  File "ApplicationHandler.py", line 376, in main
    app.geneticAlgorithm()
  File "ApplicationHandler.py", line 174, in geneticAlgorithm
    genAlgorithm.run()
  File "/home/ewoodruff/.local/lib/python3.6/site-packages/geneticalgorithm/geneticalgorithm.py", line 353, in run
    par[k]=pop[index].copy()
IndexError: index 100 is out of bounds for axis 0 with size 100

Here are the parameters I'm using:
{'max_num_iteration': 1, 'population_size': 100, 'mutation_probability': 0.1, 'elit_ratio': 0, 'crossover_probability': 0.5, 'parents_portion': 0.1, 'crossover_type': 'uniform', 'max_iteration_without_improv': None}

**Comment by PasaOpasen** [comment]
@elizabethwoodruff I've solved this bag in my supported fork: https://github.com/PasaOpasen/geneticalgorithm2
